backend/stringspot/src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Entity\User;
use ApiPlatform\Metadata\Get;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use App\Repository\ReservationRepository;
use App\State\ReservationStateProvider;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
#[ApiResource(
    provider: ReservationStateProvider::class,
    operations: [
        new Get,
        new GetCollection,
        new Post,
        new Delete
    ],
    normalizationContext: ['groups' => ['reservations']]
)]
#[ORM\HasLifecycleCallbacks]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['reservations'])]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups(['courts', 'reservations', 'user:read'])]
    private ?\DateTimeImmutable $start_time = null;

    #[ORM\Column]
    #[Groups(['courts', 'reservations', 'user:read'])]
    private ?\DateTimeImmutable $end_time = null;

    // #[ORM\Column(length: 64)]
    // #[Groups(['reservations'])]
    // private ?string $res_type = null;

    // #[ORM\Column]
    // #[Groups(['reservations', 'user:read'])]
    // private ?bool $active = null;

    #[ORM\ManyToOne(inversedBy: 'reservations', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['reservations', 'user:read'])]
    private ?Court $court = null;

    #[ORM\Column]
    #[Groups(['reservations', 'user:read'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['reservations'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToOne(inversedBy: 'reservation')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['courts', 'reservations'])]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartTime(): ?\DateTimeImmutable
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeImmutable $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeImmutable
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeImmutable $end_time): static
    {
        $this->end_time = $end_time;

        return $this;
    }

    // public function getResType(): ?string
    // {
    //     return $this->res_type;
    // }

    // public function setResType(string $res_type): static
    // {
    //     $this->res_type = $res_type;

    //     return $this;
    // }

    // public function isActive(): ?bool
    // {
    //     return $this->active;
    // }

    // public function setActive(bool $active): static
    // {
    //     $this->active = $active;

    //     return $this;
    // }

    public function getCourt(): ?Court
    {
        return $this->court;
    }

    public function setCourt(?Court $court): static
    {
        $this->court = $court;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): static
    {
        $this->createdAt = new \DateTimeImmutable();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

backend/stringspot/src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Reservation;
use ApiPlatform\Metadata\Get;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use App\Controller\MeController;
use Lexik\Bundle\JWTAuthenticationBundle\Security\User\JWTUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource(
    normalizationContext: ['groups' => ['user:read']],
    operations: [
        new Get,
        new GetCollection(name: 'get_current_user', uriTemplate: '/users/me', paginationEnabled: false, controller: MeController::class),
        new Post,
        new Delete
    ],
    denormalizationContext: ['groups' => ['user:write']]
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface, JWTUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['reservations', 'user:read', 'user:write'])]
    private ?string $email = null;

    #[ORM\Column]
    #[Groups(['user:read'])]
    private array $roles = [];

    #[Groups(['user:write'])]
    #[SerializedName('password')]
    private ?string $plainPassword = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 64)]
    #[Groups(['reservations', 'user:read', 'user:write'])]
    private ?string $first_name = null;

    #[ORM\Column(length: 64)]
    #[Groups(['reservations', 'user:read', 'user:write'])]
    private ?string $last_name = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Reservation::class, cascade: ['persist'])]
    #[Groups(['user:read'])]
    private ?Reservation $reservation = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PastRes::class, orphanRemoval: true, cascade: ['persist'])]
    #[Groups(['user:read', 'pastRes'])]
    private Collection $pastRes;

    public function __construct()
    {
        $this->pastRes = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(Reservation $reservation): static
    {
        // set the owning side of the relation if necessary
        if ($reservation->getUser() !== $this) {
            $reservation->setUser($this);
        }

        $this->reservation = $reservation;

        return $this;
    }

    /**
     * @return Collection<int, PastRes>
     */
    public function getPastRes(): Collection
    {
        return $this->pastRes;
    }

    public function addPastRes(PastRes $pastRes): static
    {
        if (!$this->pastRes->contains($pastRes)) {
            $this->pastRes->add($pastRes);
            $pastRes->setUser($this);
        }

        return $this;
    }

    public function removePastRes(PastRes $pastRes): static
    {
        if ($this->pastRes->removeElement($pastRes)) {
            // set the owning side to null (unless already changed)
            if ($pastRes->getUser() === $this) {
                $pastRes->setUser(null);
            }
        }

        return $this;
    }

    public static function createFromPayload($id, array $payload)
    {
        return (new User())->setId($id);
    }


    public function setPlainPassword(string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }
}

backend/stringspot/src/Controller/Admin/ReservationController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_admin_reservation_list', methods: ['GET'])]
    public function list(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/list.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_reservation_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_reservation_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_reservation_list', [], Response::HTTP_SEE_OTHER);
    }
}

backend/stringspot/templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_reservation_delete', { id: reservation.id }) }}" onsubmit="return confirm('Are you sure you want to delete this reservation?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}" />
  <button class="btn btn-danger btn-sm mx-1 mb-2 bi bi-trash"></button>
</form>

backend/stringspot/templates/reservation/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Reservation List
{% endblock %}
{% block resActive %}
  active
{% endblock %}
{% block subBody %}
  <div class="container-fluid">
    <h1>Reservation List</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Res #</th>
          <th>User Name</th>
          <th>Contact</th>
          <th>Date</th>
          <th>Center</th>
          <th>Court</th>
          <th>Time</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
        {% for reservation in reservations %}
          <tr>
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.user.firstName ~ ' ' ~ reservation.user.lastName }}</td>
            <td>{{ reservation.user.email }}</td>
            <td>{{ reservation.startTime|date('d-m-Y') }}</td>
            <td>{{ reservation.court.center.name }}</td>
            <td>{{ reservation.court.number }}</td>
            <td>{{ reservation.startTime|date('H:i') }}</td>
            <td>{{ reservation.createdAt|date('d-m-Y H:i') }}</td>
            <td>
              <a href="{{ path('app_admin_reservation_show', { id: reservation.id }) }}"><button type="button" class="btn btn-info btn-sm bi bi-eye"></button></a>
            </td>
            <td>{{ include('reservation/_delete_form.html.twig') }}</td>
          </tr>
        {% else %}
          <tr>
            <td colspan="8">No records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

backend/stringspot/templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Reservation
{% endblock %}

{% block body %}
  {% block subBody %}
    <div class="container-fluid">
      <h1>Reservation</h1>

      <table class="table">
        <tbody>
          <tr>
            <th>Res #</th>
            <td>{{ reservation.id }}</td>
          </tr>
          <tr>
            <th>User Name</th>
            <td>{{ reservation.user.firstName ~ ' ' ~ reservation.user.lastName }}</td>
          </tr>
          <tr>
            <th>Contact</th>
            <td>{{ reservation.user.email }}</td>
          </tr>
          <tr>
            <th>Date</th>
            <td>{{ reservation.startTime|date('Y:m:d') }}</td>
          </tr>
          <tr>
            <th>Center</th>
            <td>{{ reservation.court.center.name }}</td>
          </tr>
          <tr>
            <th>Court</th>
            <td>{{ reservation.court.number }}</td>
          </tr>
          <tr>
            <th>Time</th>
            <td>{{ reservation.startTime|date('H:i') }}</td>
          </tr>
          <tr>
            <th>Created</th>
            <td>{{ reservation.createdAt|date('d-m-Y H:i') }}</td>
          </tr>
          <tr>
            <th>Type</th>
            {% if reservation.resType == 'user' %}
              <td>User</td>
            {% else %}
              <td>Admin</td>
            {% endif %}
          </tr>
          <tr>
            <th>Active</th>
            {% if reservation.active %}
              <td>Active</td>
            {% else %}
              <td>Past</td>
            {% endif %}
          </tr>
        </tbody>
      </table>

      {{ include('reservation/_delete_form.html.twig') }}

      <a href="{{ path('app_admin_reservation_list') }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square">Back to list</button></a>
    </div>
  {% endblock %}
{% endblock %}