backend/stringspot/src/Entity/Center.php
<?php

namespace App\Entity;

use App\Entity\Court;
use ApiPlatform\Metadata\Get;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CenterRepository;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CenterRepository::class)]
#[ApiResource(
    operations: [
        new Get,
        new GetCollection,
    ],
    normalizationContext: ['groups' => ['centers']]
)]
class Center
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['centers', 'courts'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['courts', 'centers', 'countries', 'zones', 'reservations', 'user:read'])]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['centers'])]
    private ?string $address = null;

    #[ORM\ManyToOne(inversedBy: 'centers')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['centers', 'user:read'])]
    private ?Zone $zone = null;

    #[ORM\OneToMany(mappedBy: 'center', targetEntity: Court::class, orphanRemoval: true)]
    #[Groups(['centers'])]
    private Collection $courts;

    #[ORM\Column]
    #[Groups(['centers'])]
    private ?int $number_courts = null;

    #[ORM\Column]
    #[Groups(['centers'])]
    private ?float $latitude = null;

    #[ORM\Column]
    #[Groups(['centers'])]
    private ?float $longitude = null;

    public function __construct()
    {
        $this->courts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getZone(): ?Zone
    {
        return $this->zone;
    }

    public function setZone(?Zone $zone): static
    {
        $this->zone = $zone;

        return $this;
    }

    /**
     * @return Collection<int, Court>
     */
    public function getCourts(): Collection
    {
        return $this->courts;
    }

    public function addCourt(Court $court): static
    {
        if (!$this->courts->contains($court)) {
            $this->courts->add($court);
            $court->setCenter($this);
        }

        return $this;
    }

    public function removeCourt(Court $court): static
    {
        if ($this->courts->removeElement($court)) {
            // set the owning side to null (unless already changed)
            if ($court->getCenter() === $this) {
                $court->setCenter(null);
            }
        }

        return $this;
    }

    public function getNumberCourts(): ?int
    {
        return $this->number_courts;
    }

    public function setNumberCourts(int $number_courts): static
    {
        $this->number_courts = $number_courts;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }
}

backend/stringspot/src/Entity/Zone.php
<?php

namespace App\Entity;

use App\Entity\Center;
use ApiPlatform\Metadata\Get;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ZoneRepository;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ZoneRepository::class)]
#[ApiResource(
    operations: [
        new Get,
        new GetCollection()
    ],
    normalizationContext: ['groups' => ['zones']]
)]
class Zone
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['zones', 'centers'])]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    #[Groups(['courts', 'centers', 'countries', 'zones', 'reservations', 'user:read'])]
    private ?string $post_code = null;

    #[ORM\OneToMany(mappedBy: 'zone', targetEntity: Center::class)]
    #[Groups(['zones'])]
    private Collection $centers;

    #[ORM\Column(length: 64)]
    #[Groups(['courts', 'centers', 'countries', 'zones', 'reservations', 'user:read'])]
    private ?string $city = null;

    #[ORM\ManyToOne(inversedBy: 'zones')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['zones', 'centers'])]
    private ?Country $country = null;

    public function __construct()
    {
        $this->centers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(string $post_code): static
    {
        $this->post_code = $post_code;

        return $this;
    }

    /**
     * @return Collection<int, Center>
     */
    public function getCenters(): Collection
    {
        return $this->centers;
    }

    public function addCenter(Center $center): static
    {
        if (!$this->centers->contains($center)) {
            $this->centers->add($center);
            $center->setZone($this);
        }

        return $this;
    }

    public function removeCenter(Center $center): static
    {
        if ($this->centers->removeElement($center)) {
            // set the owning side to null (unless already changed)
            if ($center->getZone() === $this) {
                $center->setZone(null);
            }
        }

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): static
    {
        $this->country = $country;

        return $this;
    }
}

backend/stringspot/src/Form/ZoneType.php
<?php

namespace App\Form;

use App\Entity\Country;
use App\Entity\Zone;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ZoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('country', EntityType::class, [
            'class' => Country::class,
            'choice_label' => 'name',
            'query_builder' => function (EntityRepository $cr) {
                return $cr->createQueryBuilder('c')
                    ->orderBy('c.name', 'ASC');
            }
        ])
            ->add('post_code', TextType::class)
            ->add('post_code', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Zone::class,
        ]);
    }
}

backend/stringspot/src/Controller/Admin/ZoneController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Zone;
use App\Form\ZoneType;
use App\Repository\ZoneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/zone')]
class ZoneController extends AbstractController
{
    #[Route('/', name: 'app_admin_zone_list', methods: ['GET'])]
    public function list(ZoneRepository $zoneRepository): Response
    {
        return $this->render('zone/list.html.twig', [
            'zones' => $zoneRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_zone_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $zone = new Zone();
        $form = $this->createForm(ZoneType::class, $zone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($zone);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_zone_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('zone/new.html.twig', [
            'zone' => $zone,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_zone_show', methods: ['GET'])]
    public function show(Zone $zone): Response
    {
        return $this->render('zone/show.html.twig', [
            'zone' => $zone,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_zone_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Zone $zone, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ZoneType::class, $zone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_zone_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('zone/edit.html.twig', [
            'zone' => $zone,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_zone_delete', methods: ['POST'])]
    public function delete(Request $request, Zone $zone, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$zone->getId(), $request->request->get('_token'))) {
            $entityManager->remove($zone);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_zone_list', [], Response::HTTP_SEE_OTHER);
    }
}

backend/stringspot/templates/zone/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_zone_delete', { id: zone.id }) }}" onsubmit="return confirm('Are you sure you want to delete this zone?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ zone.id) }}" />
  <button class="btn btn-danger btn-sm mx-1 mb-2 bi bi-trash">Delete Zone</button>
</form>

backend/stringspot/templates/zone/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-warning btn-sm mx-1 mb-2 bi bi-save">{{ button_label|default(' Create') }}</button>
{{ form_end(form) }}

backend/stringspot/templates/zone/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Edit Zone
{% endblock %}

{% block body %}
  {% block subBody %}
    <div class="container-fluid">
      <h1>Edit Zone</h1>

      {{ include('zone/_form.html.twig', { button_label: 'Update' }) }}

      {{ include('zone/_delete_form.html.twig') }}
      <a href="{{ path('app_admin_zone_show', { id: zone.id }) }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square">Back to Zone Page</button></a>
    </div>
  {% endblock %}
{% endblock %}

backend/stringspot/templates/zone/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Zone List
{% endblock %}
{% block zoneActive %}
  active
{% endblock %}
{% block subBody %}
  <div class="container-fluid">
    <h1>Zone List</h1>
    <a href="{{ path('app_admin_zone_new') }}"><button type="button" class="btn btn-primary mb-3 bi bi-plus-lg"></button></a>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" style="width: 8%">Country</th>
          <th scope="col" style="width: 8%">Zone</th>
          <th scope="col" style="width: 4%">Edit</th>
          <th scope="col" style="width: 80%">Centers</th>
        </tr>
      </thead>
      <tbody>
        {% for zone in zones %}
          <tr>
            <td>{{ zone.country.name }}</td>
            <td>{{ zone.postCode }}</td>
            <td>
              <a href="{{ path('app_admin_zone_edit', { id: zone.id }) }}"><button type="button" class="btn btn-warning btn-sm bi bi-pencil-square"></button></a>
            </td>
            <td class="p-0">
              <table class="table table-hover m-0">
                <tbody>
                  {% for center in zone.centers %}
                    <tr>
                      <td class="border-bottom-0" style="width: 30%">{{ center.name|e }}</td>
                      <td class="border-bottom-0" style="width: 60%">{{ center.address|e }}</td>
                      <td style="width: 10%">
                        <a href="{{ path('app_admin_center_show', { id: center.id }) }}"><button type="button" class="btn btn-info btn-sm bi bi-eye"></button></a>
                        <a href="{{ path('app_admin_center_edit', { id: center.id }) }}"><button type="button" class="btn btn-warning btn-sm bi bi-pencil-square"></button></a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="8">No records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

backend/stringspot/templates/zone/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  New Zone
{% endblock %}

{% block body %}
  {% block subBody %}
    <div class="container-fluid">
      <h1>Create new Zone</h1>

      {{ include('zone/_form.html.twig') }}
    </div>
  {% endblock %}
{% endblock %}

backend/stringspot/templates/zone/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Zone
{% endblock %}

{% block body %}
  {% block subBody %}
    <div class="container-fluid">
      <h1>Zone</h1>
      <table class="table">
        <tbody>
          <tr>
            <th>City</th>
            <td>{{ zone.city }}</td>
          </tr>
          <tr>
            <th>Postal Code</th>
            <td>{{ zone.postCode }}</td>
          </tr>
          <tr>
            <th>Country</th>
            <td>{{ zone.country.name }}</td>
          </tr>
          <tr>
            <th>Centers</th>
            {% if zone.centers %}
              <td class="p-0">
                <table class="table table-hover m-0">
                  <tbody>
                    <tr>
                      <th scope="col" style="width: 30%">Name</th>
                      <th scope="col" style="width: 30%">Address</th>
                      <th scope="col" style="width: 30%"># of Courts</th>
                      <th scope="col" style="width: 10%">Actions</th>
                    </tr>
                    {% for center in zone.centers %}
                      <tr>
                        <td class="border-bottom-0">{{ center.name|e }}</td>
                        <td class="border-bottom-0">{{ center.address|e }}</td>
                        <td class="border-bottom-0">{{ center.numberCourts|e }}</td>
                        <td>
                          <a href="{{ path('app_admin_center_show', { id: center.id }) }}"><button type="button" class="btn btn-info btn-sm bi bi-eye"></button></a>
                          <a href="{{ path('app_admin_center_edit', { id: center.id }) }}"><button type="button" class="btn btn-warning btn-sm bi bi-pencil-square"></button></a>
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </td>
            {% endif %}
          </tr>
        </tbody>
      </table>

      <a href="{{ path('app_admin_zone_edit', { id: zone.id }) }}"><button type="button" class="btn btn-sm btn-warning mx-1 mb-2">Edit</button></a>

      {{ include('zone/_delete_form.html.twig') }}

      <a href="{{ path('app_admin_country_show', { id: zone.country.id }) }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square">Back to Country</button></a>
    </div>
  {% endblock %}
{% endblock %}